# Defines the threshold for the level of severity.
# The action will fail on any pull requests that introduce vulnerabilities of the specified severity level or higher.
# Negated while "warn-only" is set to true, however this will not always be the case.
fail_on_severity: critical
# Contains a list of strings of the build environments you want to support.
# The action will fail on pull requests that introduce vulnerabilities in the scopes that match the list.
fail_on_scopes: [runtime]
# Enable or disable reporting the review summary as a comment in the pull request.
# If enabled, you must give the workflow or job permission pull-requests: write.
comment_summary_in_pr: always
# Any number of packages (in purl format) to block in a PR.
# Unfortunately, while there is a draft purl spec for specifying a range of package versions, it is not yet merged into the actual spec.
# Until this happens, we will need to specify each version individually.
deny_packages:
  - pkg:maven/org.apache.logging.log4j/log4j-core@2.16.0
# Enable or disable retrying the action every 10 seconds while waiting for dependency submission actions to complete.
# This will have no effect on GHES until the Dependency Submission API is available.
retry_on_snapshot_warnings: true
# When set to true, the action will log all vulnerabilities as warnings regardless of the severity, and the action will complete with a success status.
# This overrides the fail-on-severity option.
# This action will eventually not warn, and instead will enforce.
warn_only: true
# We are not going to run license checks for now.
# We will look into running them later.
# This check doesn't run on GHES anyway due to limitations in the API, so enabling it would only change things in github.com
license_check: false
